server {
    listen 4200;

    location /api/ {
        proxy_pass https://api.explore21.com/api/;
        proxy_ssl_server_name on;
        proxy_set_header Host api.explore21.com;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_connect_timeout 10s;
        proxy_read_timeout 120s;
    }

    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }
}